version: '2'
services:
    frontend:
        build: ./client
        ports:
        - "3000:3000"
        depends_on:
        - backend
    backend:
        build: ./server
        ports:
        - "5001:5001"
        depends_on: 
        - db
    db:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
        - mongodata:/data/db
        restart: unless-stopped
volumes:
    mongodata: